// GEN-8145: acceptance tests for the /avatars response schemas now sourced
// from scripts/backend/avatars-api-schema.json instead of hand-written entries
// in scripts/operation-schemas.json (and, GEN-8255, the request bodies from its
// generated requests). node --test, stdlib only; the OpenAPI
// copies are parsed with PyYAML (no YAML parser ships in the Node stdlib).
import test from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { accessSync, constants, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "..", "..");
const OPENAPI = path.join(ROOT, "public", "openapi.yaml");
const OPERATION_SCHEMAS = path.join(ROOT, "scripts", "operation-schemas.json");
const AVATARS_SCHEMA = path.join(ROOT, "scripts", "backend", "avatars-api-schema.json");
const SYNC_MCP = path.join(ROOT, "scripts", "sync_mcp_surface.py");
const SYNC_BACKEND = path.join(ROOT, "scripts", "sync-from-backend.mjs");

// TMPDIR can point at a read-only mount (a locked-down lane box); fall back to
// a per-process directory under the repo before giving up.
function tempRoot() {
  for (const candidate of [tmpdir(), path.join(ROOT, ".tmp", String(process.pid))]) {
    try {
      mkdirSync(candidate, { recursive: true });
      accessSync(candidate, constants.W_OK);
      return candidate;
    } catch {
      // try the next candidate
    }
  }
  throw new Error("no writable temp directory");
}

// The OpenAPI copies are YAML generated by scripts/sync_mcp_surface.py; PyYAML
// round-trips them to the same object the generator rendered, so the committed
// file can be asserted against the vendored schemas structurally.
function parseOpenApi() {
  const script = 'import json,sys,yaml\nprint(json.dumps(yaml.safe_load(open(sys.argv[1])), separators=(",",":")))';
  const result = spawnSync("python3", ["-c", script, OPENAPI], { cwd: ROOT, encoding: "utf8" });
  assert.notEqual(result.status, null, `python3 could not run: ${result.error?.message ?? result.stderr}`);
  if (result.status !== 0) {
    throw new Error(`python3 could not parse ${OPENAPI}:\n${result.stderr}`);
  }
  return JSON.parse(result.stdout);
}

function jsonSchemaFor(operation) {
  return operation.responses["200"].content["application/json"].schema;
}

test("D1: GET /avatars/{id} 200 exposes latest_generated_video_url on avatar_talking_loops items", () => {
  const doc = parseOpenApi();
  const schema = jsonSchemaFor(doc.paths["/avatars/{id}"].get);
  const loopItems = schema.properties.avatar_looks.items.properties.avatar_talking_loops.items;
  assert.ok(
    Object.hasOwn(loopItems.properties, "latest_generated_video_url"),
    "avatar_talking_loops items lack latest_generated_video_url",
  );
});

test("D2: GET /avatars list item deep-equals the vendored summary schema", () => {
  const doc = parseOpenApi();
  const schema = jsonSchemaFor(doc.paths["/avatars"].get);
  const summary = JSON.parse(readFileSync(AVATARS_SCHEMA, "utf8")).summary;
  assert.deepEqual(schema.items, summary);
});

test("D3: operation-schemas.json carries no key under the /avatars paths", () => {
  const schemas = JSON.parse(readFileSync(OPERATION_SCHEMAS, "utf8"));
  const avatarKeys = Object.keys(schemas).filter((key) => key.split(" ")[1].startsWith("/avatars"));
  assert.deepEqual(avatarKeys, []);
});

test("D4: sync_mcp_surface.py --check fails when the vendored avatars-api-schema.json is edited by one byte", () => {
  const original = readFileSync(AVATARS_SCHEMA);
  try {
    const edited = Buffer.from(original);
    const at = edited.indexOf('"my"');
    assert.ok(at >= 0, 'vendored file should contain the "my" source enum');
    edited[at + 2] = 0x7a; // 'y' -> 'z', one byte
    assert.equal(edited.length, original.length, "the edit must change exactly one byte");
    writeFileSync(AVATARS_SCHEMA, edited);

    const result = spawnSync("python3", [SYNC_MCP, "--check"], { cwd: ROOT, encoding: "utf8" });
    assert.notEqual(result.status, null, `sync_mcp_surface.py did not run: ${result.error?.message ?? result.stderr}`);
    assert.notEqual(result.status, 0, "--check should exit non-zero after a byte edit");
    assert.match(result.stdout, /FAIL/);
  } finally {
    writeFileSync(AVATARS_SCHEMA, original);
  }
});

test("D5: sync fails clearly when the backend lacks docs/generated/avatars-api-schema.json", () => {
  const dir = mkdtempSync(path.join(tempRoot(), "avatars-d5-"));
  try {
    const result = spawnSync(process.execPath, [SYNC_BACKEND, "--backend", dir], { cwd: ROOT, encoding: "utf8" });
    assert.notEqual(result.status, null, `sync-from-backend.mjs did not run: ${result.error?.message ?? result.stderr}`);
    assert.notEqual(result.status, 0, "sync should exit non-zero when the avatars artifact is absent");
    assert.match(result.stderr, /avatars-api-schema\.json/);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

// GEN-8255: the /avatars request bodies and query parameters come from the
// vendored avatars-api-schema.json `requests`, generated from the params the
// backend controllers permit; there is no hand-written request list.
function vendoredRequests() {
  return JSON.parse(readFileSync(AVATARS_SCHEMA, "utf8")).requests;
}

function bodySchema(operation) {
  return operation.requestBody.content["application/json"].schema;
}

test("D6: avatar upload request bodies deep-equal the vendored requests, clone_voice params included", () => {
  const doc = parseOpenApi();
  const requests = vendoredRequests();
  const loopBody = bodySchema(doc.paths["/avatars/{avatar_id}/talking_loops"].post);
  const avatarBody = bodySchema(doc.paths["/avatars"].post);
  assert.deepEqual(loopBody, requests["POST /v1/avatars/{avatar_id}/talking_loops"].schema);
  assert.deepEqual(avatarBody, requests["POST /v1/avatars"].schema);
  for (const name of ["clone_voice", "voice_gender", "voice_language"]) {
    assert.ok(Object.hasOwn(loopBody.properties, name), `talking_loops POST lacks ${name}`);
  }
  assert.ok(Object.hasOwn(avatarBody.properties, "clone_voice"), "POST /avatars lacks clone_voice");
});

test("D7: GET /avatars query parameters are the vendored requests and no hand-written request file exists", () => {
  const doc = parseOpenApi();
  const query = (doc.paths["/avatars"].get.parameters ?? []).filter((param) => param.in === "query").map((param) => param.name);
  assert.deepEqual(query.sort(), Object.keys(vendoredRequests()["GET /v1/avatars"].schema.properties).sort());
  assert.throws(() => accessSync(path.join(ROOT, "scripts", "avatars-request-bodies.json")));
});
