// Acceptance tests for the /characters schemas (avatars are called characters).
// The response schemas come from scripts/backend/characters-api-schema.json, not
// hand-written entries in scripts/operation-schemas.json, and the request bodies
// from its generated `requests`. node --test, stdlib only; the OpenAPI copies are
// parsed with PyYAML (no YAML parser ships in the Node stdlib).
import test from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { accessSync, constants, copyFileSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "..", "..");
const OPENAPI = path.join(ROOT, "public", "openapi.yaml");
const OPERATION_SCHEMAS = path.join(ROOT, "scripts", "operation-schemas.json");
const AVATARS_SCHEMA = path.join(ROOT, "scripts", "backend", "avatars-api-schema.json");
const CHARACTERS_SCHEMA = path.join(ROOT, "scripts", "backend", "characters-api-schema.json");
const SURFACE = path.join(ROOT, "scripts", "mcp-surface.json");
const SYNC_MCP = path.join(ROOT, "scripts", "sync_mcp_surface.py");
const SYNC_BACKEND = path.join(ROOT, "scripts", "sync-from-backend.mjs");

// TMPDIR can point at a read-only mount (a locked-down lane box); fall back to
// a per-process directory under the repo before giving up.
function tempRoot() {
  for (const candidate of [tmpdir(), path.join(ROOT, ".tmp", String(process.pid))]) {
    try {
      mkdirSync(candidate, { recursive: true });
      accessSync(candidate, constants.W_OK);
      return candidate;
    } catch {
      // try the next candidate
    }
  }
  throw new Error("no writable temp directory");
}

// The OpenAPI copies are YAML generated by scripts/sync_mcp_surface.py; PyYAML
// round-trips them to the same object the generator rendered, so the committed
// file can be asserted against the vendored schemas structurally.
function parseOpenApi() {
  const script = 'import json,sys,yaml\nprint(json.dumps(yaml.safe_load(open(sys.argv[1])), separators=(",",":")))';
  const result = spawnSync("python3", ["-c", script, OPENAPI], { cwd: ROOT, encoding: "utf8" });
  assert.notEqual(result.status, null, `python3 could not run: ${result.error?.message ?? result.stderr}`);
  if (result.status !== 0) {
    throw new Error(`python3 could not parse ${OPENAPI}:\n${result.stderr}`);
  }
  return JSON.parse(result.stdout);
}

function jsonSchemaFor(operation) {
  return operation.responses["200"].content["application/json"].schema;
}

function vendoredCharacters() {
  return JSON.parse(readFileSync(CHARACTERS_SCHEMA, "utf8"));
}

test("D1: GET /characters/{id} 200 exposes latest_generated_video_url on each look's talking_characters items", () => {
  const doc = parseOpenApi();
  const schema = jsonSchemaFor(doc.paths["/characters/{id}"].get);
  const items = schema.properties.looks.items.properties.talking_characters.items;
  assert.ok(
    Object.hasOwn(items.properties, "latest_generated_video_url"),
    "looks[].talking_characters items lack latest_generated_video_url",
  );
});

test("D2: GET /characters list item deep-equals the vendored summary schema", () => {
  const doc = parseOpenApi();
  const schema = jsonSchemaFor(doc.paths["/characters"].get);
  assert.deepEqual(schema.items, vendoredCharacters().summary);
});

test("D3: operation-schemas.json carries no key under the /characters or /avatars paths", () => {
  const schemas = JSON.parse(readFileSync(OPERATION_SCHEMAS, "utf8"));
  const keys = Object.keys(schemas).filter((key) => /^\/(characters|avatars)/.test(key.split(" ")[1]));
  assert.deepEqual(keys, []);
});

test("D4: sync_mcp_surface.py --check fails when the vendored characters-api-schema.json is edited by one byte", () => {
  const original = readFileSync(CHARACTERS_SCHEMA);
  try {
    const edited = Buffer.from(original);
    const at = edited.indexOf('"my"');
    assert.ok(at >= 0, 'vendored file should contain the "my" source enum');
    edited[at + 2] = 0x7a; // 'y' -> 'z', one byte
    assert.equal(edited.length, original.length, "the edit must change exactly one byte");
    writeFileSync(CHARACTERS_SCHEMA, edited);

    const result = spawnSync("python3", [SYNC_MCP, "--check"], { cwd: ROOT, encoding: "utf8" });
    assert.notEqual(result.status, null, `sync_mcp_surface.py did not run: ${result.error?.message ?? result.stderr}`);
    assert.notEqual(result.status, 0, "--check should exit non-zero after a byte edit");
    assert.match(result.stdout, /FAIL/);
  } finally {
    writeFileSync(CHARACTERS_SCHEMA, original);
  }
});

function runSyncAgainst(dir) {
  const result = spawnSync(process.execPath, [SYNC_BACKEND, "--backend", dir], { cwd: ROOT, encoding: "utf8" });
  assert.notEqual(result.status, null, `sync-from-backend.mjs did not run: ${result.error?.message ?? result.stderr}`);
  return result;
}

test("D5: sync fails clearly when the backend lacks docs/generated/avatars-api-schema.json", () => {
  const dir = mkdtempSync(path.join(tempRoot(), "avatars-d5-"));
  try {
    const result = runSyncAgainst(dir);
    assert.notEqual(result.status, 0, "sync should exit non-zero when the avatars artifact is absent");
    assert.match(result.stderr, /avatars-api-schema\.json/);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("D5b: sync fails clearly when the backend lacks docs/generated/characters-api-schema.json", () => {
  const dir = mkdtempSync(path.join(tempRoot(), "characters-d5-"));
  try {
    mkdirSync(path.join(dir, "docs", "generated"), { recursive: true });
    copyFileSync(AVATARS_SCHEMA, path.join(dir, "docs", "generated", "avatars-api-schema.json"));
    const result = runSyncAgainst(dir);
    assert.notEqual(result.status, 0, "sync should exit non-zero when the characters artifact is absent");
    assert.match(result.stderr, /characters-api-schema\.json/);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

function bodySchema(operation) {
  return operation.requestBody.content["application/json"].schema;
}

test("D6: character upload request bodies deep-equal the vendored requests, clone_voice params included", () => {
  const doc = parseOpenApi();
  const requests = vendoredCharacters().requests;
  const talkingBody = bodySchema(doc.paths["/characters/{character_id}/talking_characters"].post);
  const characterBody = bodySchema(doc.paths["/characters"].post);
  assert.deepEqual(talkingBody, requests["POST /v1/characters/{character_id}/talking_characters"].schema);
  assert.deepEqual(characterBody, requests["POST /v1/characters"].schema);
  for (const name of ["clone_voice", "voice_gender", "voice_language"]) {
    assert.ok(Object.hasOwn(talkingBody.properties, name), `talking_characters POST lacks ${name}`);
  }
  assert.ok(Object.hasOwn(characterBody.properties, "clone_voice"), "POST /characters lacks clone_voice");
});

test("D7: GET /characters query parameters are the vendored requests and no hand-written request file exists", () => {
  const doc = parseOpenApi();
  const query = (doc.paths["/characters"].get.parameters ?? []).filter((param) => param.in === "query").map((param) => param.name);
  assert.deepEqual(query.sort(), Object.keys(vendoredCharacters().requests["GET /v1/characters"].schema.properties).sort());
  assert.throws(() => accessSync(path.join(ROOT, "scripts", "avatars-request-bodies.json")));
  assert.throws(() => accessSync(path.join(ROOT, "scripts", "characters-request-bodies.json")));
});

// The characters schema is vendored and every gen_characters route is documented
// under /characters, from that schema, with its deprecated /avatars name noted.
test("D8: the characters schema is vendored and every gen_characters route is documented from it", () => {
  const characters = vendoredCharacters();
  assert.ok(characters.requests, "vendored characters-api-schema.json has no requests");
  for (const name of ["summary", "detail", "create", "look", "talking_character", "talking_character_create"]) {
    assert.ok(characters[name], `vendored characters-api-schema.json lacks ${name}`);
  }

  const doc = parseOpenApi();
  const surface = JSON.parse(readFileSync(SURFACE, "utf8")).operations.filter((entry) => entry.mcp_tool === "gen_characters");
  assert.ok(surface.length >= 9, `only ${surface.length} gen_characters operations on the MCP surface`);
  for (const entry of surface) {
    const key = `${entry.method} /v1${entry.path}`;
    assert.ok(Object.hasOwn(characters.requests, key), `${key} is not a route of the vendored characters schema`);
    const operation = doc.paths[entry.path]?.[entry.method.toLowerCase()];
    assert.ok(operation, `${entry.method} ${entry.path} is not documented`);
    assert.equal(operation["x-mcp-tool"], "gen_characters");
    assert.deepEqual(operation.tags, ["Characters"]);
    const alias = entry.path
      .replace(/^\/characters/, "/avatars")
      .replace("{character_id}", "{avatar_id}")
      .replace("/talking_characters", "/talking_loops");
    assert.ok(
      operation.description.includes(`${entry.method} /v1${alias}`) && /deprecated/.test(operation.description),
      `${entry.method} ${entry.path} does not name its deprecated alias ${alias}`,
    );
  }

  const paths = Object.keys(doc.paths);
  assert.deepEqual(paths.filter((route) => route.startsWith("/avatars")), [], "/avatars is documented as its own operation");
  const avatarTools = paths.flatMap((route) =>
    Object.values(doc.paths[route]).filter((op) => op?.["x-mcp-tool"] === "gen_avatars").map(() => route),
  );
  assert.deepEqual(avatarTools, [], "an operation still names the retired gen_avatars tool");
});
